version: "3.8"

services:

  web:
    build:
      context: .
    command: 
      - sh 
      - -c 
      - | 
        cd storyhub
        python manage.py makemigrations --no-input
        python manage.py migrate --no-input
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
      