# Generated by Django 4.1.7 on 2023-03-26 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_options_remove_post_bookmark_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmarkpost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="bookmarkpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
