# Generated by Django 4.1.7 on 2023-04-21 09:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_likepost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="posts_cover_pics"
            ),
        ),
    ]
