# Generated by Django 4.1.7 on 2023-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="admin@gmail.com",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
            preserve_default=False,
        ),
    ]
