# Generated by Django 4.1.7 on 2023-03-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="users.userprofile"
            ),
        ),
    ]
